# Generated by Django 5.2.17 on 2026-08-19 17:50

import django.core.validators
import django.db.models.deletion
import watchlist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedticker',
            name='recompute_interval_hours',
            field=models.PositiveIntegerField(default=watchlist.models._default_recompute_hours, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2160)]),
        ),
        migrations.AddField(
            model_name='watchedticker',
            name='refresh_interval_hours',
            field=models.PositiveIntegerField(default=watchlist.models._default_refresh_hours, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.CreateModel(
            name='StockPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitative', models.JSONField(blank=True, default=dict)),
                ('quantitative_summary', models.JSONField(blank=True, default=dict)),
                ('qualitative', models.JSONField(blank=True, default=dict)),
                ('qualitative_summary', models.JSONField(blank=True, default=dict)),
                ('data_synthetic', models.BooleanField(default=False)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='core.watchedticker')),
            ],
        ),
        migrations.CreateModel(
            name='QuantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('compressed', models.BinaryField()),
                ('watched_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.watchedticker')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['watched_ticker', '-taken_at'], name='core_quants_watched_02cfad_idx')],
            },
        ),
    ]
