# Generated by Django 4.2.30 on 2026-08-08 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=16)),
                ('indicator', models.CharField(choices=[('Z_SCORE', 'Z-Score'), ('RSI', 'RSI'), ('SMA_CROSS', 'SMA Spread (fast-slow)'), ('MACD_HIST', 'MACD Histogram'), ('PCT_CHANGE', '% Change'), ('VOLATILITY', 'Volatility (annualized)'), ('PRICE', 'Price')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('operator', models.CharField(choices=[('<', 'less than'), ('>', 'greater than'), ('<=', 'at most'), ('>=', 'at least'), ('==', 'equal to'), ('cross_above', 'crosses above'), ('cross_below', 'crosses below')], max_length=12)),
                ('threshold', models.FloatField()),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='active', max_length=10)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=15)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_metric_value', models.FloatField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=16)),
                ('indicator', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=12)),
                ('threshold', models.FloatField()),
                ('metric_value', models.FloatField()),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_rationale', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('delivery', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='strategies.strategy')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['status', 'last_evaluated_at'], name='strategies__status_21ad22_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'is_read'], name='strategies__workspa_c4a5ea_idx'),
        ),
    ]
