# Generated by Django 4.2.30 on 2026-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_alert_data_synthetic'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', '-created_at'], name='strategies__workspa_52647e_idx'),
        ),
    ]
