# Generated by Django 4.2.30 on 2026-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_alter_alert_metric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
