# Generated by Django 4.2.30 on 2026-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_alert_data_synthetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
