# Generated by Django 4.2.30 on 2026-08-10 17:44
import uuid

from django.db import migrations, models

import engine.models


def _randomize_existing_secrets(apps, schema_editor):
    """AddField evaluates the callable default ONCE, stamping the same secret on
    every pre-existing row — re-randomize so each strategy's HMAC key is unique."""
    Strategy = apps.get_model("strategies", "Strategy")
    for pk in Strategy.objects.values_list("pk", flat=True).iterator():
        Strategy.objects.filter(pk=pk).update(webhook_secret=uuid.uuid4().hex)


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_strategy_consecutive_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='webhook_secret',
            field=models.CharField(default=engine.models._new_webhook_secret, editable=False, max_length=64),
        ),
        migrations.RunPython(_randomize_existing_secrets, migrations.RunPython.noop),
    ]
