# Generated by Django 4.2.30 on 2026-08-08 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='operator',
            field=models.CharField(choices=[('<', 'less than'), ('>', 'greater than'), ('<=', 'at most'), ('>=', 'at least'), ('cross_above', 'crosses above'), ('cross_below', 'crosses below')], max_length=12),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='poll_interval_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
