# Generated by Django 4.2.30 on 2026-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_alter_strategy_cooldown_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='condition_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='strategy',
            name='condition',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='indicator',
            field=models.CharField(choices=[('Z_SCORE', 'Z-Score'), ('RSI', 'RSI'), ('SMA_CROSS', 'SMA Spread (fast-slow)'), ('MACD_HIST', 'MACD Histogram'), ('PCT_CHANGE', '% Change'), ('VOLATILITY', 'Volatility (annualized)'), ('SMA', 'SMA'), ('EMA', 'EMA'), ('PRICE', 'Price')], max_length=20),
        ),
    ]
