# Generated by Django 4.2.30 on 2026-08-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_alert_condition_detail_strategy_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='data_synthetic',
            field=models.BooleanField(default=False),
        ),
    ]
