# Generated by Django 5.1.15 on 2026-08-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_alert_strategies__workspa_52647e_idx'),
        ('strategies', '0007_strategy_webhook_secret'),
    ]

    operations = [
    ]
